# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'SturicousApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for SturicousApp
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod "Parse"
  pod "MessageInputBar"
  inherit! :search_paths
    

end
