# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'SturicousApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for SturicousApp
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'Parse'
  pod 'MessageInputBar'
  pod 'AFNetworking'
  pod 'BDBOAuth1Manager'

  target 'SturicousAppTests' do
    inherit! :search_paths
    # Pods for testing
   pod 'Parse'
  end

  target 'SturicousAppUITests' do
    # Pods for testing
   pod 'Parse'
  end

end